apiVersion: apps/v1
kind: Deployment
metadata:
  name: dnsapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dns_app
  template:
    metadata:
      labels:
        app: dns_app
    spec:
      containers:
      - name: us
        image: docker.io/qm2104/dns/us:latest
        ports:
        - containerPort: 8080
      - name: as
        image: docker.io/qm2104/dns/as:latest
        ports:
        - containerPort: 53533
      - name: fs
        image: docker.io/qm2104/dns/fs:latest
        ports:
        - containerPort: 9090

---
apiVersion: v1
kind: Service
metadata:
  name: us
spec:
  ports:
  - port: 8080
    targetPort: 30003
  selector:
    name: us
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: as
spec:
  ports:
  - port: 53533
    targetPort: 30001
  selector:
    name: as
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: fs
spec:
  ports:
  - port: 9090
    targetPort: 30002
  selector:
    name: fs
  type: NodePort